<?php
/**
 * @file
 * A module that loads up the currentStarCraft 2
 * Grandmaster ladders with known Barcodes real identities.
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function barcodes_exposed_help($path, $arg) {
  switch ($path) {
    case "admin/help#barcodes_exposed":
      return '<p>' . t("Load up the current StarCraft 2 Grandmaster ladders with known Barcodes real identities.") . '</p>';
      break;
  }
}

/**
 * Implements hook_block_info().
 */
function barcodes_exposed_block_info() {
  $blocks['barcodes_exposed'] = array(
    // The name that will appear in the block list.
    'info' => t('Barcodes Exposed')
  );

  $blocks['barcodes_exposed_alt'] = array(
    // The name that will appear in the block list.
    'info' => t('Barcodes Exposed Alt')
  );

  return $blocks;
}

/**
 * Custom content function.
 *
 * Set beginning and end dates, retrieve posts from database
 * saved in that time period.
 *
 * @return
 *   A result set of the targeted posts.
 */
function barcodes_exposed_contents() {
  // Get today's date
  $today = getDate();
  // Calculate the date a week ago
  $start_time = mktime(0, 0, 0, $today['mon'], ($today['mday'] - 7), $today['year']);
  // Get all posts from one week ago to the present
  $end_time = time();

  // Use Database API to retrieve current posts
  $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title', 'created'))
    ->condition('status', 1) // Published
    ->condition('created', array($start_time, $end_time), 'BETWEEN')
    ->orderBy('created', 'DESC') // Most recent first
    ->execute();
  return $query;
}
